import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'zh' | 'es' | 'fr' | 'vi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionaries
const translations = {
  en: {
    // Time
    'load' : 'Load',
    'hide' : 'Hide',
    'series': 'Saved Data',
    'time' : 'Processing Time',
    'subject': 'Subject',

    'math' : 'Math',
    'physics': 'Physics',
    'chemistry': 'Chemistry',
    'Biology': 'Biology',
    // App Navigation
    'nav.learnsphere': 'LearnSphere',
    'nav.solver': 'Smart Solver',
    'nav.learningroad': 'Learning Road',
    'nav.settings': 'Settings',
    'nav.practiceexam': 'Practice Exam',
    'nav.signout': 'Sign Out',
    
    // LearnSphere
    'learnsphere.title': 'LearnSphere',
    'learnsphere.subtitle': 'Transform Your Text',
    'learnsphere.description': 'LearnSphere is an AI-powered virtual tutor that revolutionizes education by providing personalized lessons and exam preparation to students in even the most remote and underserved communities.',
    'learnsphere.perfect': ' No Wi-Fi,No Data,No Cost.',
    'learnsphere.tone': 'Choose Writing Tone',
    'learnsphere.placeholder': 'Paste your text here to make it sound more human and natural...',
    'learnsphere.humanize': 'Humanize',
    'learnsphere.humanizing': 'Humanizing...',
    'learnsphere.characters': 'characters',
    
    // Tones
    'tone.professional': 'Professional',
    'tone.casual': 'Casual',
    'tone.friendly': 'Friendly',
    'tone.academic': 'Academic',
    'tone.creative': 'Creative',
    'tone.conversational': 'Conversational',
    
    // solver
    'solver.title': 'Smart Solver',
    'solver.subtitle': 'AI Problem Solver',
    'solver.hero.title': 'Upload. Solve. Learn.',
    'solver.hero.description': 'Upload images or PDFs containing problems, and our AI will solve them step-by-step with detailed explanations to help you understand the process.',
    'solver.upload.title': 'Upload Problems',
    'solver.upload.click': 'Click to upload files',
    'solver.upload.support': 'Support for JPG, PNG, PDF files (Max 10MB each)',
    'solver.upload.camera': 'Take Photo',
    'solver.upload.files': 'Uploaded Files:',
    'solver.solve': 'Solve Problems',
    'solver.solving': 'Solving Problems...',
    'solver.analyzing': 'Analyzing with Gemini AI',
    'solver.reading': 'Reading your problems and generating step-by-step solutions...',
    'solver.powered': 'Powered by Google Gemini',
    'solver.found': 'Found',
    'solver.problems': 'Problems',
    'solver.problem': 'Problem',
    'solver.click.steps': 'Click to see step-by-step solutions',
    'solver.solution': 'Solution:',
    'solver.steps': 'steps',
    'solver.back.problems': 'Back to Problems',
    'solver.final.answer': 'Final Answer:',
    'solver.step': 'Step',
    'solver.equation': 'Equation:',
    'solver.explanation': 'Explanation:',
    'solver.previous': 'Previous Step',
    'solver.next': 'Next Step',
    'solver.new.upload': 'New Upload',
    
    // Learning Road
    'learningroad.title': 'Learning Road',
    'learningroad.description': 'Enter a topic you want to learn and get a personalized learning path.',
    'learningroad.what.learn': 'What do you want to learn?',
    'learningroad.placeholder': 'Enter a topic (e.g., JavaScript, Machine Learning, Photography)',
    'learningroad.generate': 'Generate Learning Path',
    'learningroad.generating': 'Generating Path...',
    'learningroad.powered': 'Powered by Google Gemini',
    'learningroad.path': 'Learning Path:',
    'learningroad.steps': 'steps',
    'learningroad.minutes': 'minutes',
    'learningroad.completed': 'completed',
    'learningroad.duration': 'Duration',
    'learningroad.key.topics': 'Key Topics',
    'learningroad.start.learning': 'Start Learning',
    'learningroad.take.quiz': 'Take Quiz',
    'learningroad.new.path': 'New Learning Path',
    'learningroad.introduction': 'Introduction',
    'learningroad.examples': 'Examples:',
    'learningroad.key.points': 'Key Points',
    'learningroad.summary': 'Summary',
    'learningroad.next.steps': 'Next Steps',
    'learningroad.mark.complete': 'Mark as Complete',
    'learningroad.continue': 'Continue Learning',
    'learningroad.quiz.complete': 'Quiz Complete!',
    'learningroad.your.score': 'Your Score:',
    'learningroad.your.answer': 'Your answer:',
    'learningroad.correct.answer': 'Correct answer:',
    'learningroad.question': 'Question',
    'learningroad.finish.quiz': 'Finish Quiz',
    'learningroad.next.question': 'Next Question',
    'learningroad.generating.material': 'Generating Learning Material...',
    'learningroad.generating.quiz': 'Generating Quiz...',
    'learningroad.creating.content': 'Creating personalized content for you',
    'learningroad.creating.questions': 'Creating personalized questions for you',
    
    // Practice Exam
    'practiceexam.title': 'Practice Exam Generator',
    'practiceexam.subtitle': 'AI-Powered Exam Creation',
    
    // Exam Simulator
    'examsimulator.time' : 'Exam Time',
    'examsimulator.time.tip' : 'Add time limit in minute like real exam. If none enter a number you want',

    'examsimulator.title': 'Exam Simulator',
    'examsimulator.subtitle': 'Generate progressive difficulty exam series',
    'examsimulator.hero.title': 'Create Practice Exams Instantly',
    'examsimulator.hero.description': 'Generate comprehensive practice exams from your study materials. Upload documents or describe your exam requirements, and our AI will create a professional exam series for you.',
    'examsimulator.name.title': 'Name Your Exam Series',
    'examsimulator.name.placeholder': 'e.g., Advanced Calculus Practice Series, Biology Final Prep, SAT Math Bootcamp...',
    'examsimulator.name.tip': 'Give your exam series a memorable name for easy identification later',
    'examsimulator.describe.title': 'Describe Your Exam Topic',
    'examsimulator.describe.placeholder': 'e.g., Advanced Calculus concepts including derivatives, integrals, and differential equations...',
    'examsimulator.describe.tip': 'Describe the subject matter and specific topics you want to be tested on',
    'examsimulator.upload.title': 'Upload Reference Materials (Optional)',
    'examsimulator.upload.click': 'Click to upload reference materials',
    'examsimulator.upload.support': 'Support for PDF, DOC, DOCX, TXT, JPG, PNG files (Max 10MB each)',
    'examsimulator.upload.files': 'Uploaded Files:',
    'examsimulator.settings.title': 'Simulator Settings',
    'examsimulator.settings.show': 'Show Simulator Settings',
    'examsimulator.settings.hide': 'Hide Simulator Settings',
    'examsimulator.exams.number': 'Number of Progressive Exams',
    'examsimulator.exams.single': 'Single Level',
    'examsimulator.exams.basic': 'Basic → Advanced',
    'examsimulator.exams.expert': 'Basic → Expert',
    'examsimulator.exams.foundation': 'Foundation → Expert',
    'examsimulator.exams.genius': 'Foundation → Genius',
    'examsimulator.exams.tip': 'Each exam increases in difficulty. If you can score 80%+ on the final exam, you\'ve mastered the topic!',
    'examsimulator.difficulty.title': 'Progressive Difficulty Levels',
    'examsimulator.difficulty.foundation': 'Foundation',
    'examsimulator.difficulty.beginner': 'Beginner',
    'examsimulator.difficulty.intermediate': 'Intermediate',
    'examsimulator.difficulty.advanced': 'Advanced',
    'examsimulator.difficulty.expert': 'Expert',
    'examsimulator.difficulty.master': 'Master',
    'examsimulator.difficulty.genius': 'Genius',
    'examsimulator.generate': 'Generate Practice Exams',
    'examsimulator.generating': 'Generating Exam Series...',
    'examsimulator.generating.description': 'Creating progressive difficulty exams with AI...',
    'examsimulator.saved.title': 'Saved Exam Series',
    'examsimulator.saved.show': 'Load Saved Series',
    'examsimulator.saved.hide': 'Hide',
    'examsimulator.saved.empty': 'No saved exam series found. Generate your first series to see it here!',
    'examsimulator.saved.created': 'Created',
    'examsimulator.saved.exams': 'exams',
    'examsimulator.saved.load': 'Load Series',
    'examsimulator.error.title': 'Generation Error',
    'examsimulator.error.description': 'Failed to generate exam series',
    'examsimulator.error.try': 'Try Again',
    'examsimulator.error.reset': 'Reset Form',
    'practiceexam.hero.title': 'Create Practice Exams Instantly',
    'practiceexam.hero.description': 'Generate comprehensive practice exams from your study materials. Upload documents or describe your exam requirements, and our AI will create a professional PDF exam for you.',
    'practiceexam.description.title': 'Exam Description',
    'practiceexam.description.what': 'What should this exam cover?',
    'practiceexam.description.placeholder': 'e.g., Introduction to Machine Learning concepts including supervised learning, neural networks, and model evaluation...',
    'practiceexam.description.tip': 'Tip: Be specific about topics, difficulty level, and any particular areas you want to focus on.',
    'practiceexam.upload.title': 'Upload Reference Materials',
    'practiceexam.upload.click': 'Click to upload files',
    'practiceexam.upload.support': 'Support for PDF, DOC, DOCX, TXT files (Max 10MB each)',
    'practiceexam.upload.files': 'Uploaded Files:',
    'practiceexam.settings': 'Settings',
    'practiceexam.exam.settings': 'Exam Settings',
    'practiceexam.questions.count': 'Number of Questions',
    'practiceexam.time.limit': 'Time Limit (minutes)',
    'practiceexam.difficulty': 'Difficulty Level',
    'practiceexam.question.types': 'Question Types',
    'practiceexam.answer.key': 'Include Answer Key',
    'practiceexam.generate': 'Generate Practice Exam',
    'practiceexam.generating': 'Generating Exam...',
    'practiceexam.success': 'Exam Generated Successfully!',
    'practiceexam.ready': 'Ready for download',
    'practiceexam.questions': 'Questions:',
    'practiceexam.time': 'Time:',
    'practiceexam.download': 'Download PDF',
    'practiceexam.preview': 'Preview',
    'practiceexam.reset': 'Reset',
    'practiceexam.how.works': 'How It Works',
    'practiceexam.create': 'Create your perfect practice exam',
    
    // Difficulty levels
    'difficulty.easy': 'Easy',
    'difficulty.medium': 'Medium',
    'difficulty.hard': 'Hard',
    'difficulty.mixed': 'Mixed',
    'difficulty.beginner': 'Beginner',
    'difficulty.intermediate': 'Intermediate',
    'difficulty.advanced': 'Advanced',
    
    // Common
    'common.back': 'Back',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.ok': 'OK',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.language': 'Language',
    
    // Auth
    'auth.signin': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgot': 'Forgot Password?',
    'auth.no.account': "Don't have an account?",
    'auth.have.account': 'Already have an account?',
    'auth.signing.in': 'Signing in...',
    'auth.test.login': 'Auto-fill Test Login',
    'auth.terms': 'By signing in, you are agreeing to the Terms of Service, Acceptable Use Policy, and Privacy Policy.',
  },
  
  zh: {
    // Time
    'load' : '加载',
    'hide' : '隐藏',
    'series': '已保存数据',
    'time' : '处理时间',
    // App Navigation
    'nav.learnsphere': 'LearnSphere',
    'nav.solver': 'Smart Solver',
    'nav.learningroad': '学习路径',
    'nav.practiceexam': '练习考试',
    'nav.signout': '退出登录',
    'math': '数学',
    'physics': '物理',
    'chemistry': '化学',
    'biology': '生物',
    
    // LearnSphere
    'learnsphere.title': 'LearnSphere',
    'learnsphere.subtitle': '转换您的文本',
    'learnsphere.description': 'LearnSphere 是一款离线优先、由人工智能驱动的虚拟导师，通过为最偏远和服务欠缺社区的学生提供个性化课程和考试准备，彻底改变了教育。',
    'learnsphere.perfect': '无需 Wi-Fi，无需数据，无需费用。',
    'learnsphere.tone': '选择写作语调',
    'learnsphere.placeholder': '在此粘贴您的文本，使其听起来更人性化和自然...',
    'learnsphere.humanize': '人性化',
    'learnsphere.humanizing': '正在人性化...',
    'learnsphere.characters': '字符',
    
    // Tones
    'tone.professional': '专业',
    'tone.casual': '随意',
    'tone.friendly': '友好',
    'tone.academic': '学术',
    'tone.creative': '创意',
    'tone.conversational': '对话',
    
    // solver
    'solver.title': 'Smart Solver',
    'solver.subtitle': 'AI数学问题解决器',
    'solver.hero.title': '上传。解决。学习。',
    'solver.hero.description': '上传包含数学问题的图像或PDF，我们的AI将逐步解决它们，并提供详细解释帮助您理解过程。',
    'solver.upload.title': '上传数学问题',
    'solver.upload.click': '点击上传文件',
    'solver.upload.support': '支持JPG、PNG、PDF文件（每个最大10MB）',
    'solver.upload.camera': '拍照',
    'solver.upload.files': '已上传文件：',
    'solver.solve': '解决数学问题',
    'solver.solving': '正在解决问题...',
    'solver.analyzing': '使用Gemini AI分析',
    'solver.reading': '正在读取您的数学问题并生成逐步解决方案...',
    'solver.powered': '由Google Gemini提供支持',
    'solver.found': '找到',
    'solver.problems': '个问题',
    'solver.problem': '问题',
    'solver.click.steps': '点击查看逐步解决方案',
    'solver.solution': '解决方案：',
    'solver.steps': '步骤',
    'solver.back.problems': '返回问题',
    'solver.final.answer': '最终答案：',
    'solver.step': '步骤',
    'solver.equation': '方程：',
    'solver.explanation': '解释：',
    'solver.previous': '上一步',
    'solver.next': '下一步',
    'solver.new.upload': '新上传',
    
    // Learning Road
    'learningroad.title': '学习路径',
    'learningroad.description': '输入您想学习的主题，获得个性化的学习路径。',
    'learningroad.what.learn': '您想学习什么？',
    'learningroad.placeholder': '输入主题（例如：JavaScript、机器学习、摄影）',
    'learningroad.generate': '生成学习路径',
    'learningroad.generating': '正在生成路径...',
    'learningroad.powered': '由Google Gemini提供支持',
    'learningroad.path': '学习路径：',
    'learningroad.steps': '步骤',
    'learningroad.minutes': '分钟',
    'learningroad.completed': '已完成',
    'learningroad.duration': '持续时间',
    'learningroad.key.topics': '关键主题',
    'learningroad.start.learning': '开始学习',
    'learningroad.take.quiz': '参加测验',
    'learningroad.new.path': '新学习路径',
    'learningroad.introduction': '介绍',
    'learningroad.examples': '示例：',
    'learningroad.key.points': '关键要点',
    'learningroad.summary': '总结',
    'learningroad.next.steps': '下一步',
    'learningroad.mark.complete': '标记为完成',
    'learningroad.continue': '继续学习',
    'learningroad.quiz.complete': '测验完成！',
    'learningroad.your.score': '您的分数：',
    'learningroad.your.answer': '您的答案：',
    'learningroad.correct.answer': '正确答案：',
    'learningroad.question': '问题',
    'learningroad.finish.quiz': '完成测验',
    'learningroad.next.question': '下一题',
    'learningroad.generating.material': '正在生成学习材料...',
    'learningroad.generating.quiz': '正在生成测验...',
    'learningroad.creating.content': '为您创建个性化内容',
    'learningroad.creating.questions': '为您创建个性化问题',
    
    // Practice Exam
    'practiceexam.title': '练习考试生成器',
    'practiceexam.subtitle': 'AI驱动的考试创建',
    
    // Exam Simulator
    'examsimulator.time' : '考试时间',
    'examsimulator.time.tip' : '像真实考试一样以分钟为单位添加时间限制。如果没有，请输入您想要的数字',
    'examsimulator.title': '考试模拟器',
    'examsimulator.subtitle': '生成渐进难度考试系列',
    'examsimulator.hero.title': '即时创建练习考试',
    'examsimulator.hero.description': '从您的学习材料生成全面的练习考试。上传文档或描述您的考试要求，我们的AI将为您创建专业的考试系列。',
    'examsimulator.name.title': '命名您的考试系列',
    'examsimulator.name.placeholder': '例如：高级微积分练习系列、生物期末准备、SAT数学训练营...',
    'examsimulator.name.tip': '为您的考试系列起一个容易记住的名字，便于以后识别',
    'examsimulator.describe.title': '描述您的考试主题',
    'examsimulator.describe.placeholder': '例如：高级微积分概念，包括导数、积分和微分方程...',
    'examsimulator.describe.tip': '描述主题内容和您想要测试的具体主题',
    'examsimulator.upload.title': '上传参考材料（可选）',
    'examsimulator.upload.click': '点击上传参考材料',
    'examsimulator.upload.support': '支持PDF、DOC、DOCX、TXT、JPG、PNG文件（每个最大10MB）',
    'examsimulator.upload.files': '已上传文件：',
    'examsimulator.settings.title': '模拟器设置',
    'examsimulator.settings.show': '显示模拟器设置',
    'examsimulator.settings.hide': '隐藏模拟器设置',
    'examsimulator.exams.number': '渐进考试数量',
    'examsimulator.exams.single': '单一级别',
    'examsimulator.exams.basic': '基础 → 高级',
    'examsimulator.exams.expert': '基础 → 专家',
    'examsimulator.exams.foundation': '基础 → 专家',
    'examsimulator.exams.genius': '基础 → 天才',
    'examsimulator.exams.tip': '每个考试难度递增。如果您能在最终考试中得到80%+的分数，您就掌握了这个主题！',
    'examsimulator.difficulty.title': '渐进难度级别',
    'examsimulator.difficulty.foundation': '基础',
    'examsimulator.difficulty.beginner': '初学者',
    'examsimulator.difficulty.intermediate': '中级',
    'examsimulator.difficulty.advanced': '高级',
    'examsimulator.difficulty.expert': '专家',
    'examsimulator.difficulty.master': '大师',
    'examsimulator.difficulty.genius': '天才',
    'examsimulator.generate': '生成练习考试',
    'examsimulator.generating': '正在生成考试系列...',
    'examsimulator.generating.description': '使用AI创建渐进难度考试...',
    'examsimulator.saved.title': '已保存的考试系列',
    'examsimulator.saved.show': '加载已保存系列',
    'examsimulator.saved.hide': '隐藏',
    'examsimulator.saved.empty': '未找到已保存的考试系列。生成您的第一个系列以在此处查看！',
    'examsimulator.saved.created': '创建时间',
    'examsimulator.saved.exams': '考试',
    'examsimulator.saved.load': '加载系列',
    'examsimulator.error.title': '生成错误',
    'examsimulator.error.description': '生成考试系列失败',
    'examsimulator.error.try': '重试',
    'examsimulator.error.reset': '重置表单',
    'practiceexam.hero.title': '即时创建练习考试',
    'practiceexam.hero.description': '从您的学习材料生成全面的练习考试。上传文档或描述您的考试要求，我们的AI将为您创建专业的PDF考试。',
    'practiceexam.description.title': '考试描述',
    'practiceexam.description.what': '这个考试应该涵盖什么？',
    'practiceexam.description.placeholder': '例如：机器学习概念介绍，包括监督学习、神经网络和模型评估...',
    'practiceexam.description.tip': '提示：具体说明主题、难度级别和您想重点关注的任何特定领域。',
    'practiceexam.upload.title': '上传参考材料',
    'practiceexam.upload.click': '点击上传文件',
    'practiceexam.upload.support': '支持PDF、DOC、DOCX、TXT文件（每个最大10MB）',
    'practiceexam.upload.files': '已上传文件：',
    'practiceexam.settings': '设置',
    'practiceexam.exam.settings': '考试设置',
    'practiceexam.questions.count': '问题数量',
    'practiceexam.time.limit': '时间限制（分钟）',
    'practiceexam.difficulty': '难度级别',
    'practiceexam.question.types': '问题类型',
    'practiceexam.answer.key': '包含答案键',
    'practiceexam.generate': '生成练习考试',
    'practiceexam.generating': '正在生成考试...',
    'practiceexam.success': '考试生成成功！',
    'practiceexam.ready': '准备下载',
    'practiceexam.questions': '问题：',
    'practiceexam.time': '时间：',
    'practiceexam.download': '下载PDF',
    'practiceexam.preview': '预览',
    'practiceexam.reset': '重置',
    'practiceexam.how.works': '工作原理',
    'practiceexam.create': '创建您的完美练习考试',
    
    // Difficulty levels
    'difficulty.easy': '简单',
    'difficulty.medium': '中等',
    'difficulty.hard': '困难',
    'difficulty.mixed': '混合',
    'difficulty.beginner': '初学者',
    'difficulty.intermediate': '中级',
    'difficulty.advanced': '高级',
    
    // Common
    'common.back': '返回',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.close': '关闭',
    'common.ok': '确定',
    'common.yes': '是',
    'common.no': '否',
    'common.language': '语言',
    
    // Auth
    'auth.signin': '登录',
    'auth.signup': '注册',
    'auth.email': '电子邮件',
    'auth.password': '密码',
    'auth.forgot': '忘记密码？',
    'auth.no.account': '没有账户？',
    'auth.have.account': '已有账户？',
    'auth.signing.in': '正在登录...',
    'auth.test.login': '自动填充测试登录',
    'auth.terms': '通过登录，您同意服务条款、可接受使用政策和隐私政策。',
  },
  
  es: {
    // Time
    'load' : 'Cargar',
    'hide' : 'Ocultar',
    'series': 'Datos Guardados',
    'time' : 'Tiempo de Procesamiento',
    // App Navigation
    'nav.learnsphere': 'LearnSphere',
    'nav.solver': 'Smart Solver',
    'nav.learningroad': 'Ruta de Aprendizaje',
    'nav.practiceexam': 'Examen de Práctica',
    'nav.signout': 'Cerrar Sesión',
    'math': 'Matemáticas',
    'physics': 'Física',
    'chemistry': 'Química',
    'biology': 'Biología',
    
    // LearnSphere
    'learnsphere.title': 'LearnSphere',
    'learnsphere.subtitle': 'Transforma Tu Texto',
    'learnsphere.description': 'LearnSphere es un tutor virtual sin conexión, impulsado por IA, que revoluciona la educación al proporcionar lecciones personalizadas y preparación para exámenes a estudiantes incluso en las comunidades más remotas y desatendidas.',
    'learnsphere.perfect': 'Sin Wi-Fi, Sin Datos, Sin Costo.',
    'learnsphere.tone': 'Elige el Tono de Escritura',
    'learnsphere.placeholder': 'Pega tu texto aquí para hacerlo sonar más humano y natural...',
    'learnsphere.humanize': 'Humanizar',
    'learnsphere.humanizing': 'Humanizando...',
    'learnsphere.characters': 'caracteres',
    
    // Tones
    'tone.professional': 'Profesional',
    'tone.casual': 'Casual',
    'tone.friendly': 'Amigable',
    'tone.academic': 'Académico',
    'tone.creative': 'Creativo',
    'tone.conversational': 'Conversacional',
    
    // solver
    'solver.title': 'Smart Solver',
    'solver.subtitle': 'Solucionador de Problemas IA',
    'solver.hero.title': 'Sube. Resuelve. Aprende.',
    'solver.hero.description': 'Sube imágenes o PDFs con problemas matemáticos, y nuestra IA los resolverá paso a paso con explicaciones detalladas para ayudarte a entender el proceso.',
    'solver.upload.title': 'Subir Problemas Matemáticos',
    'solver.upload.click': 'Haz clic para subir archivos',
    'solver.upload.support': 'Soporte para archivos JPG, PNG, PDF (Máx 10MB cada uno)',
    'solver.upload.camera': 'Tomar Foto',
    'solver.upload.files': 'Archivos Subidos:',
    'solver.solve': 'Resolver Problemas Matemáticos',
    'solver.solving': 'Resolviendo Problemas...',
    'solver.analyzing': 'Analizando con Gemini IA',
    'solver.reading': 'Leyendo tus problemas matemáticos y generando soluciones paso a paso...',
    'solver.powered': 'Impulsado por Google Gemini',
    'solver.found': 'Encontrados',
    'solver.problems': 'Problemas',
    'solver.problem': 'Problema',
    'solver.click.steps': 'Haz clic para ver soluciones paso a paso',
    'solver.solution': 'Solución:',
    'solver.steps': 'pasos',
    'solver.back.problems': 'Volver a Problemas',
    'solver.final.answer': 'Respuesta Final:',
    'solver.step': 'Paso',
    'solver.equation': 'Ecuación:',
    'solver.explanation': 'Explicación:',
    'solver.previous': 'Paso Anterior',
    'solver.next': 'Siguiente Paso',
    'solver.new.upload': 'Nueva Subida',
    
    // Learning Road
    'learningroad.title': 'Ruta de Aprendizaje',
    'learningroad.description': 'Ingresa un tema que quieras aprender y obtén una ruta de aprendizaje personalizada.',
    'learningroad.what.learn': '¿Qué quieres aprender?',
    'learningroad.placeholder': 'Ingresa un tema (ej., JavaScript, Aprendizaje Automático, Fotografía)',
    'learningroad.generate': 'Generar Ruta de Aprendizaje',
    'learningroad.generating': 'Generando Ruta...',
    'learningroad.powered': 'Impulsado por Google Gemini',
    'learningroad.path': 'Ruta de Aprendizaje:',
    'learningroad.steps': 'pasos',
    'learningroad.minutes': 'minutos',
    'learningroad.completed': 'completados',
    'learningroad.duration': 'Duración',
    'learningroad.key.topics': 'Temas Clave',
    'learningroad.start.learning': 'Comenzar Aprendizaje',
    'learningroad.take.quiz': 'Tomar Quiz',
    'learningroad.new.path': 'Nueva Ruta de Aprendizaje',
    'learningroad.introduction': 'Introducción',
    'learningroad.examples': 'Ejemplos:',
    'learningroad.key.points': 'Puntos Clave',
    'learningroad.summary': 'Resumen',
    'learningroad.next.steps': 'Siguientes Pasos',
    'learningroad.mark.complete': 'Marcar como Completo',
    'learningroad.continue': 'Continuar Aprendiendo',
    'learningroad.quiz.complete': '¡Quiz Completado!',
    'learningroad.your.score': 'Tu Puntuación:',
    'learningroad.your.answer': 'Tu respuesta:',
    'learningroad.correct.answer': 'Respuesta correcta:',
    'learningroad.question': 'Pregunta',
    'learningroad.finish.quiz': 'Terminar Quiz',
    'learningroad.next.question': 'Siguiente Pregunta',
    'learningroad.generating.material': 'Generando Material de Aprendizaje...',
    'learningroad.generating.quiz': 'Generando Quiz...',
    'learningroad.creating.content': 'Creando contenido personalizado para ti',
    'learningroad.creating.questions': 'Creando preguntas personalizadas para ti',
    
    // Practice Exam
    'practiceexam.title': 'Generador de Exámenes de Práctica',
    'practiceexam.subtitle': 'Creación de Exámenes con IA',
    
    // Exam Simulator
    'examsimulator.time' : 'Tiempo del Examen',
    'examsimulator.time.tip' : 'Agregue el límite de tiempo en minutos como en un examen real. Si no hay, ingrese un número que desee',
    'examsimulator.title': 'Simulador de Exámenes',
    'examsimulator.subtitle': 'Generar series de exámenes de dificultad progresiva',
    'examsimulator.hero.title': 'Crea Exámenes de Práctica al Instante',
    'examsimulator.hero.description': 'Genera exámenes de práctica completos a partir de tus materiales de estudio. Sube documentos o describe los requisitos de tu examen, y nuestra IA creará una serie de exámenes profesional para ti.',
    'examsimulator.name.title': 'Nombra Tu Serie de Exámenes',
    'examsimulator.name.placeholder': 'ej., Serie de Práctica de Cálculo Avanzado, Preparación Final de Biología, Bootcamp de Matemáticas SAT...',
    'examsimulator.name.tip': 'Dale a tu serie de exámenes un nombre memorable para fácil identificación posterior',
    'examsimulator.describe.title': 'Describe Tu Tema de Examen',
    'examsimulator.describe.placeholder': 'ej., Conceptos de Cálculo Avanzado incluyendo derivadas, integrales y ecuaciones diferenciales...',
    'examsimulator.describe.tip': 'Describe la materia y temas específicos que quieres que sean evaluados',
    'examsimulator.upload.title': 'Subir Materiales de Referencia (Opcional)',
    'examsimulator.upload.click': 'Haz clic para subir materiales de referencia',
    'examsimulator.upload.support': 'Soporte para archivos PDF, DOC, DOCX, TXT, JPG, PNG (Máx 10MB cada uno)',
    'examsimulator.upload.files': 'Archivos Subidos:',
    'examsimulator.settings.title': 'Configuración del Simulador',
    'examsimulator.settings.show': 'Mostrar Configuración del Simulador',
    'examsimulator.settings.hide': 'Ocultar Configuración del Simulador',
    'examsimulator.exams.number': 'Número de Exámenes Progresivos',
    'examsimulator.exams.single': 'Nivel Único',
    'examsimulator.exams.basic': 'Básico → Avanzado',
    'examsimulator.exams.expert': 'Básico → Experto',
    'examsimulator.exams.foundation': 'Fundación → Experto',
    'examsimulator.exams.genius': 'Fundación → Genio',
    'examsimulator.exams.tip': 'Cada examen aumenta en dificultad. ¡Si puedes obtener 80%+ en el examen final, has dominado el tema!',
    'examsimulator.difficulty.title': 'Niveles de Dificultad Progresiva',
    'examsimulator.difficulty.foundation': 'Fundación',
    'examsimulator.difficulty.beginner': 'Principiante',
    'examsimulator.difficulty.intermediate': 'Intermedio',
    'examsimulator.difficulty.advanced': 'Avanzado',
    'examsimulator.difficulty.expert': 'Experto',
    'examsimulator.difficulty.master': 'Maestro',
    'examsimulator.difficulty.genius': 'Genio',
    'examsimulator.generate': 'Generar Exámenes de Práctica',
    'examsimulator.generating': 'Generando Serie de Exámenes...',
    'examsimulator.generating.description': 'Creando exámenes de dificultad progresiva con IA...',
    'examsimulator.saved.title': 'Series de Exámenes Guardadas',
    'examsimulator.saved.show': 'Cargar Series Guardadas',
    'examsimulator.saved.hide': 'Ocultar',
    'examsimulator.saved.empty': '¡No se encontraron series de exámenes guardadas. Genera tu primera serie para verla aquí!',
    'examsimulator.saved.created': 'Creado',
    'examsimulator.saved.exams': 'exámenes',
    'examsimulator.saved.load': 'Cargar Serie',
    'examsimulator.error.title': 'Error de Generación',
    'examsimulator.error.description': 'Falló la generación de la serie de exámenes',
    'examsimulator.error.try': 'Intentar de Nuevo',
    'examsimulator.error.reset': 'Reiniciar Formulario',
    'practiceexam.hero.title': 'Crea Exámenes de Práctica al Instante',
    'practiceexam.hero.description': 'Genera exámenes de práctica completos a partir de tus materiales de estudio. Sube documentos o describe los requisitos de tu examen, y nuestra IA creará un examen PDF profesional para ti.',
    'practiceexam.description.title': 'Descripción del Examen',
    'practiceexam.description.what': '¿Qué debería cubrir este examen?',
    'practiceexam.description.placeholder': 'ej., Introducción a conceptos de Aprendizaje Automático incluyendo aprendizaje supervisado, redes neuronales y evaluación de modelos...',
    'practiceexam.description.tip': 'Consejo: Sé específico sobre temas, nivel de dificultad y cualquier área particular en la que quieras enfocarte.',
    'practiceexam.upload.title': 'Subir Materiales de Referencia',
    'practiceexam.upload.click': 'Haz clic para subir archivos',
    'practiceexam.upload.support': 'Soporte para archivos PDF, DOC, DOCX, TXT (Máx 10MB cada uno)',
    'practiceexam.upload.files': 'Archivos Subidos:',
    'practiceexam.settings': 'Configuración',
    'practiceexam.exam.settings': 'Configuración del Examen',
    'practiceexam.questions.count': 'Número de Preguntas',
    'practiceexam.time.limit': 'Límite de Tiempo (minutos)',
    'practiceexam.difficulty': 'Nivel de Dificultad',
    'practiceexam.question.types': 'Tipos de Preguntas',
    'practiceexam.answer.key': 'Incluir Clave de Respuestas',
    'practiceexam.generate': 'Generar Examen de Práctica',
    'practiceexam.generating': 'Generando Examen...',
    'practiceexam.success': '¡Examen Generado Exitosamente!',
    'practiceexam.ready': 'Listo para descargar',
    'practiceexam.questions': 'Preguntas:',
    'practiceexam.time': 'Tiempo:',
    'practiceexam.download': 'Descargar PDF',
    'practiceexam.preview': 'Vista Previa',
    'practiceexam.reset': 'Reiniciar',
    'practiceexam.how.works': 'Cómo Funciona',
    'practiceexam.create': 'Crea tu examen de práctica perfecto',
    
    // Difficulty levels
    'difficulty.easy': 'Fácil',
    'difficulty.medium': 'Medio',
    'difficulty.hard': 'Difícil',
    'difficulty.mixed': 'Mixto',
    'difficulty.beginner': 'Principiante',
    'difficulty.intermediate': 'Intermedio',
    'difficulty.advanced': 'Avanzado',
    
    // Common
    'common.back': 'Atrás',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.close': 'Cerrar',
    'common.ok': 'OK',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.language': 'Idioma',
    
    // Auth
    'auth.signin': 'Iniciar Sesión',
    'auth.signup': 'Registrarse',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.forgot': '¿Olvidaste tu Contraseña?',
    'auth.no.account': '¿No tienes una cuenta?',
    'auth.have.account': '¿Ya tienes una cuenta?',
    'auth.signing.in': 'Iniciando sesión...',
    'auth.test.login': 'Auto-llenar Login de Prueba',
    'auth.terms': 'Al iniciar sesión, aceptas los Términos de Servicio, Política de Uso Aceptable y Política de Privacidad.',
  },
  
  fr: {
    // Time
    'load' : 'Charger',
    'hide' : 'Masquer',
    'series': 'Données Sauvegardées',
    'time' : 'Temps de Traitement',
    // App Navigation
    'nav.learnsphere': 'LearnSphere',
    'nav.solver': 'Smart Solver',
    'nav.learningroad': 'Parcours d\'Apprentissage',
    'nav.practiceexam': 'Examen d\'Entraînement',
    'nav.signout': 'Se Déconnecter',
    'math': 'Mathématiques',
    'physics': 'Physique',
    'chemistry': 'Chimie',
    'biology': 'Biologie',
    
    // LearnSphere
    'learnsphere.title': 'LearnSphere',
    'learnsphere.subtitle': 'Transformez Votre Texte',
    'learnsphere.description': 'LearnSphere est un tuteur virtuel hors ligne, alimenté par l\'IA, qui révolutionne l\'éducation en fournissant des leçons personnalisées et une préparation aux examens aux étudiants, même dans les communautés les plus éloignées et les moins bien desservies.',
    'learnsphere.perfect': 'Pas de Wi-Fi, Pas de Données, Pas de Coût.',
    'learnsphere.tone': 'Choisir le Ton d\'Écriture',
    'learnsphere.placeholder': 'Collez votre texte ici pour le rendre plus humain et naturel...',
    'learnsphere.humanize': 'Humaniser',
    'learnsphere.humanizing': 'Humanisation...',
    'learnsphere.characters': 'caractères',
    
    // Tones
    'tone.professional': 'Professionnel',
    'tone.casual': 'Décontracté',
    'tone.friendly': 'Amical',
    'tone.academic': 'Académique',
    'tone.creative': 'Créatif',
    'tone.conversational': 'Conversationnel',
    
    // solver
    'solver.title': 'Smart Solver',
    'solver.subtitle': 'Résolveur de Problèmes Mathématiques IA',
    'solver.hero.title': 'Téléchargez. Résolvez. Apprenez.',
    'solver.hero.description': 'Téléchargez des images ou PDFs contenant des problèmes mathématiques, et notre IA les résoudra étape par étape avec des explications détaillées pour vous aider à comprendre le processus.',
    'solver.upload.title': 'Télécharger des Problèmes Mathématiques',
    'solver.upload.click': 'Cliquez pour télécharger des fichiers',
    'solver.upload.support': 'Support pour fichiers JPG, PNG, PDF (Max 10MB chacun)',
    'solver.upload.camera': 'Prendre une Photo',
    'solver.upload.files': 'Fichiers Téléchargés:',
    'solver.solve': 'Résoudre les Problèmes Mathématiques',
    'solver.solving': 'Résolution des Problèmes...',
    'solver.analyzing': 'Analyse avec Gemini IA',
    'solver.reading': 'Lecture de vos problèmes mathématiques et génération de solutions étape par étape...',
    'solver.powered': 'Alimenté par Google Gemini',
    'solver.found': 'Trouvé',
    'solver.problems': 'Problèmes',
    'solver.problem': 'Problème',
    'solver.click.steps': 'Cliquez pour voir les solutions étape par étape',
    'solver.solution': 'Solution:',
    'solver.steps': 'étapes',
    'solver.back.problems': 'Retour aux Problèmes',
    'solver.final.answer': 'Réponse Finale:',
    'solver.step': 'Étape',
    'solver.equation': 'Équation:',
    'solver.explanation': 'Explication:',
    'solver.previous': 'Étape Précédente',
    'solver.next': 'Étape Suivante',
    'solver.new.upload': 'Nouveau Téléchargement',
    
    // Learning Road
    'learningroad.title': 'Parcours d\'Apprentissage',
    'learningroad.description': 'Entrez un sujet que vous voulez apprendre et obtenez un parcours d\'apprentissage personnalisé.',
    'learningroad.what.learn': 'Que voulez-vous apprendre?',
    'learningroad.placeholder': 'Entrez un sujet (ex., JavaScript, Apprentissage Automatique, Photographie)',
    'learningroad.generate': 'Générer un Parcours d\'Apprentissage',
    'learningroad.generating': 'Génération du Parcours...',
    'learningroad.powered': 'Alimenté par Google Gemini',
    'learningroad.path': 'Parcours d\'Apprentissage:',
    'learningroad.steps': 'étapes',
    'learningroad.minutes': 'minutes',
    'learningroad.completed': 'complétées',
    'learningroad.duration': 'Durée',
    'learningroad.key.topics': 'Sujets Clés',
    'learningroad.start.learning': 'Commencer l\'Apprentissage',
    'learningroad.take.quiz': 'Passer le Quiz',
    'learningroad.new.path': 'Nouveau Parcours d\'Apprentissage',
    'learningroad.introduction': 'Introduction',
    'learningroad.examples': 'Exemples:',
    'learningroad.key.points': 'Points Clés',
    'learningroad.summary': 'Résumé',
    'learningroad.next.steps': 'Prochaines Étapes',
    'learningroad.mark.complete': 'Marquer comme Terminé',
    'learningroad.continue': 'Continuer l\'Apprentissage',
    'learningroad.quiz.complete': 'Quiz Terminé!',
    'learningroad.your.score': 'Votre Score:',
    'learningroad.your.answer': 'Votre réponse:',
    'learningroad.correct.answer': 'Réponse correcte:',
    'learningroad.question': 'Question',
    'learningroad.finish.quiz': 'Terminer le Quiz',
    'learningroad.next.question': 'Question Suivante',
    'learningroad.generating.material': 'Génération du Matériel d\'Apprentissage...',
    'learningroad.generating.quiz': 'Génération du Quiz...',
    'learningroad.creating.content': 'Création de contenu personnalisé pour vous',
    'learningroad.creating.questions': 'Création de questions personnalisées pour vous',
    
    // Practice Exam
    'practiceexam.title': 'Générateur d\'Examens d\'Entraînement',
    'practiceexam.subtitle': 'Création d\'Examens Alimentée par IA',
    
    // Exam Simulator
    'examsimulator.time' : 'Temps de l\'Examen',
    'examsimulator.time.tip' : 'Ajoutez une limite de temps en minutes comme pour un vrai examen. Si aucune, entrez le nombre de votre choix',
    'examsimulator.title': 'Simulateur d\'Examens',
    'examsimulator.subtitle': 'Générer des séries d\'examens de difficulté progressive',
    'examsimulator.hero.title': 'Créez des Examens d\'Entraînement Instantanément',
    'examsimulator.hero.description': 'Générez des examens d\'entraînement complets à partir de vos matériaux d\'étude. Téléchargez des documents ou décrivez vos exigences d\'examen, et notre IA créera une série d\'examens professionnelle pour vous.',
    'examsimulator.name.title': 'Nommez Votre Série d\'Examens',
    'examsimulator.name.placeholder': 'ex., Série de Pratique de Calcul Avancé, Préparation Finale de Biologie, Bootcamp de Mathématiques SAT...',
    'examsimulator.name.tip': 'Donnez à votre série d\'examens un nom mémorable pour une identification facile plus tard',
    'examsimulator.describe.title': 'Décrivez Votre Sujet d\'Examen',
    'examsimulator.describe.placeholder': 'ex., Concepts de Calcul Avancé incluant les dérivées, intégrales et équations différentielles...',
    'examsimulator.describe.tip': 'Décrivez la matière et les sujets spécifiques que vous voulez être testés',
    'examsimulator.upload.title': 'Télécharger des Matériaux de Référence (Optionnel)',
    'examsimulator.upload.click': 'Cliquez pour télécharger des matériaux de référence',
    'examsimulator.upload.support': 'Support pour fichiers PDF, DOC, DOCX, TXT, JPG, PNG (Max 10MB chacun)',
    'examsimulator.upload.files': 'Fichiers Téléchargés:',
    'examsimulator.settings.title': 'Paramètres du Simulateur',
    'examsimulator.settings.show': 'Afficher les Paramètres du Simulateur',
    'examsimulator.settings.hide': 'Masquer les Paramètres du Simulateur',
    'examsimulator.exams.number': 'Nombre d\'Examens Progressifs',
    'examsimulator.exams.single': 'Niveau Unique',
    'examsimulator.exams.basic': 'Basique → Avancé',
    'examsimulator.exams.expert': 'Basique → Expert',
    'examsimulator.exams.foundation': 'Fondation → Expert',
    'examsimulator.exams.genius': 'Fondation → Génie',
    'examsimulator.exams.tip': 'Chaque examen augmente en difficulté. Si vous pouvez obtenir 80%+ à l\'examen final, vous avez maîtrisé le sujet!',
    'examsimulator.difficulty.title': 'Niveaux de Difficulté Progressive',
    'examsimulator.difficulty.foundation': 'Fondation',
    'examsimulator.difficulty.beginner': 'Débutant',
    'examsimulator.difficulty.intermediate': 'Intermédiaire',
    'examsimulator.difficulty.advanced': 'Avancé',
    'examsimulator.difficulty.expert': 'Expert',
    'examsimulator.difficulty.master': 'Maître',
    'examsimulator.difficulty.genius': 'Génie',
    'examsimulator.generate': 'Générer des Examens de Pratique',
    'examsimulator.generating': 'Génération de la Série d\'Examens...',
    'examsimulator.generating.description': 'Création d\'examens de difficulté progressive avec IA...',
    'examsimulator.saved.title': 'Séries d\'Examens Sauvegardées',
    'examsimulator.saved.show': 'Charger les Séries Sauvegardées',
    'examsimulator.saved.hide': 'Masquer',
    'examsimulator.saved.empty': 'Aucune série d\'examens sauvegardée trouvée. Générez votre première série pour la voir ici!',
    'examsimulator.saved.created': 'Créé',
    'examsimulator.saved.exams': 'examens',
    'examsimulator.saved.load': 'Charger la Série',
    'examsimulator.error.title': 'Erreur de Génération',
    'examsimulator.error.description': 'Échec de la génération de la série d\'examens',
    'examsimulator.error.try': 'Réessayer',
    'examsimulator.error.reset': 'Réinitialiser le Formulaire',
    'practiceexam.hero.title': 'Créez des Examens d\'Entraînement Instantanément',
    'practiceexam.hero.description': 'Générez des examens d\'entraînement complets à partir de vos matériaux d\'étude. Téléchargez des documents ou décrivez vos exigences d\'examen, et notre IA créera un examen PDF professionnel pour vous.',
    'practiceexam.description.title': 'Description de l\'Examen',
    'practiceexam.description.what': 'Que devrait couvrir cet examen?',
    'practiceexam.description.placeholder': 'ex., Introduction aux concepts d\'Apprentissage Automatique incluant l\'apprentissage supervisé, les réseaux de neurones et l\'évaluation de modèles...',
    'practiceexam.description.tip': 'Conseil: Soyez spécifique sur les sujets, le niveau de difficulté et les domaines particuliers sur lesquels vous voulez vous concentrer.',
    'practiceexam.upload.title': 'Télécharger des Matériaux de Référence',
    'practiceexam.upload.click': 'Cliquez pour télécharger des fichiers',
    'practiceexam.upload.support': 'Support pour fichiers PDF, DOC, DOCX, TXT (Max 10MB chacun)',
    'practiceexam.upload.files': 'Fichiers Téléchargés:',
    'practiceexam.settings': 'Paramètres',
    'practiceexam.exam.settings': 'Paramètres de l\'Examen',
    'practiceexam.questions.count': 'Nombre de Questions',
    'practiceexam.time.limit': 'Limite de Temps (minutes)',
    'practiceexam.difficulty': 'Niveau de Difficulté',
    'practiceexam.question.types': 'Types de Questions',
    'practiceexam.answer.key': 'Inclure le Corrigé',
    'practiceexam.generate': 'Générer l\'Examen d\'Entraînement',
    'practiceexam.generating': 'Génération de l\'Examen...',
    'practiceexam.success': 'Examen Généré avec Succès!',
    'practiceexam.ready': 'Prêt pour téléchargement',
    'practiceexam.questions': 'Questions:',
    'practiceexam.time': 'Temps:',
    'practiceexam.download': 'Télécharger PDF',
    'practiceexam.preview': 'Aperçu',
    'practiceexam.reset': 'Réinitialiser',
    'practiceexam.how.works': 'Comment ça Marche',
    'practiceexam.create': 'Créez votre examen d\'entraînement parfait',
    
    // Difficulty levels
    'difficulty.easy': 'Facile',
    'difficulty.medium': 'Moyen',
    'difficulty.hard': 'Difficile',
    'difficulty.mixed': 'Mixte',
    'difficulty.beginner': 'Débutant',
    'difficulty.intermediate': 'Intermédiaire',
    'difficulty.advanced': 'Avancé',
    
    // Common
    'common.back': 'Retour',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.save': 'Sauvegarder',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.close': 'Fermer',
    'common.ok': 'OK',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.language': 'Langue',
    
    // Auth
    'auth.signin': 'Se Connecter',
    'auth.signup': 'S\'Inscrire',
    'auth.email': 'Email',
    'auth.password': 'Mot de Passe',
    'auth.forgot': 'Mot de Passe Oublié?',
    'auth.no.account': 'Pas de compte?',
    'auth.have.account': 'Déjà un compte?',
    'auth.signing.in': 'Connexion...',
    'auth.test.login': 'Remplir Automatiquement la Connexion Test',
    'auth.terms': 'En vous connectant, vous acceptez les Conditions de Service, la Politique d\'Utilisation Acceptable et la Politique de Confidentialité.',
  },
  
  vi: {
    // Time
    'load' : 'Tải',
    'hide' : 'Ẩn',
    'series': 'Dữ liệu đã lưu',
    'time' : 'Thời gian xử lý',
    // App Navigation
    'nav.learnsphere': 'LearnSphere',
    'nav.solver': 'Smart Solver',
    'nav.learningroad': 'Con Đường Học Tập',
    'nav.practiceexam': 'Bài Thi Thực Hành',
    'nav.signout': 'Đăng Xuất',

    'math': 'Toán',
    'physics': 'Vật lý',
    'chemistry': 'Hóa học',
    'biology': 'Sinh học',
    
    // LearnSphere
    'learnsphere.title': 'LearnSphere',
    'learnsphere.subtitle': 'Biến đổi văn bản của bạn',
    'learnsphere.description': 'LearnSphere là một gia sư ảo hoạt động ngoại tuyến, được hỗ trợ bởi AI, cách mạng hóa giáo dục bằng cách cung cấp các bài học cá nhân hóa và luyện thi cho học sinh ngay cả ở những cộng đồng xa xôi và kém may mắn nhất.',
    'learnsphere.perfect': 'Không Wi-Fi, Không Dữ liệu, Không Chi phí.',
    'learnsphere.tone': 'Chọn Giọng Điệu Viết',
    'learnsphere.placeholder': 'Dán văn bản của bạn vào đây để làm cho nó nghe tự nhiên và giống con người hơn...',
    'learnsphere.humanize': 'Nhân Hóa',
    'learnsphere.humanizing': 'Đang Nhân Hóa...',
    'learnsphere.characters': 'ký tự',
    
    // Tones
    'tone.professional': 'Chuyên Nghiệp',
    'tone.casual': 'Thông Thường',
    'tone.friendly': 'Thân Thiện',
    'tone.academic': 'Học Thuật',
    'tone.creative': 'Sáng Tạo',
    'tone.conversational': 'Đối Thoại',
    
    // solver
    'solver.title': 'Smart Solver',
    'solver.subtitle': 'Trình Giải AI',
    'solver.hero.title': 'Tải Lên. Giải Quyết. Học Hỏi.',
    'solver.hero.description': 'Tải lên hình ảnh hoặc PDF chứa bài toán, và AI của chúng tôi sẽ giải chúng từng bước với giải thích chi tiết để giúp bạn hiểu quy trình.',
    'solver.upload.title': 'Tải Lên Bài Toán',
    'solver.upload.click': 'Nhấp để tải lên tệp',
    'solver.upload.support': 'Hỗ trợ tệp JPG, PNG, PDF (Tối đa 10MB mỗi tệp)',
    'solver.upload.camera': 'Chụp Ảnh',
    'solver.upload.files': 'Tệp Đã Tải Lên:',
    'solver.solve': 'Giải Bài Toán',
    'solver.solving': 'Đang Giải Bài Toán...',
    'solver.analyzing': 'Phân Tích với Gemini AI',
    'solver.reading': 'Đang đọc bài toán của bạn và tạo giải pháp từng bước...',
    'solver.powered': 'Được Hỗ Trợ bởi Google Gemini',
    'solver.found': 'Tìm Thấy',
    'solver.problems': 'Bài Toán',
    'solver.problem': 'Bài Toán',
    'solver.click.steps': 'Nhấp để xem giải pháp từng bước',
    'solver.solution': 'Giải Pháp:',
    'solver.steps': 'bước',
    'solver.back.problems': 'Quay Lại Bài Toán',
    'solver.final.answer': 'Đáp Án Cuối Cùng:',
    'solver.step': 'Bước',
    'solver.equation': 'Phương Trình:',
    'solver.explanation': 'Giải Thích:',
    'solver.previous': 'Bước Trước',
    'solver.next': 'Bước Tiếp Theo',
    'solver.new.upload': 'Tải Lên Mới',
    
    // Learning Road
    'learningroad.title': 'Lộ Trình Học Tập',
    'learningroad.description': 'Nhập chủ đề bạn muốn học và nhận lộ trình học tập cá nhân hóa.',
    'learningroad.what.learn': 'Bạn muốn học gì?',
    'learningroad.placeholder': 'Nhập chủ đề (ví dụ: JavaScript, Học Máy, Nhiếp Ảnh)',
    'learningroad.generate': 'Tạo Lộ Trình Học Tập',
    'learningroad.generating': 'Đang Tạo Lộ Trình...',
    'learningroad.powered': 'Được Hỗ Trợ bởi Google Gemini',
    'learningroad.path': 'Lộ Trình Học Tập:',
    'learningroad.steps': 'bước',
    'learningroad.minutes': 'phút',
    'learningroad.completed': 'hoàn thành',
    'learningroad.duration': 'Thời Gian',
    'learningroad.key.topics': 'Chủ Đề Chính',
    'learningroad.start.learning': 'Bắt Đầu Học',
    'learningroad.take.quiz': 'Làm Bài Quiz',
    'learningroad.new.path': 'Lộ Trình Học Tập Mới',
    'learningroad.introduction': 'Giới Thiệu',
    'learningroad.examples': 'Ví Dụ:',
    'learningroad.key.points': 'Điểm Chính',
    'learningroad.summary': 'Tóm Tắt',
    'learningroad.next.steps': 'Bước Tiếp Theo',
    'learningroad.mark.complete': 'Đánh Dấu Hoàn Thành',
    'learningroad.continue': 'Tiếp Tục Học',
    'learningroad.quiz.complete': 'Quiz Hoàn Thành!',
    'learningroad.your.score': 'Điểm Của Bạn:',
    'learningroad.your.answer': 'Câu trả lời của bạn:',
    'learningroad.correct.answer': 'Câu trả lời đúng:',
    'learningroad.question': 'Câu Hỏi',
    'learningroad.finish.quiz': 'Hoàn Thành Quiz',
    'learningroad.next.question': 'Câu Hỏi Tiếp Theo',
    'learningroad.generating.material': 'Đang Tạo Tài Liệu Học Tập...',
    'learningroad.generating.quiz': 'Đang Tạo Quiz...',
    'learningroad.creating.content': 'Tạo nội dung cá nhân hóa cho bạn',
    'learningroad.creating.questions': 'Tạo câu hỏi cá nhân hóa cho bạn',
    
    // Practice Exam
    'practiceexam.title': 'Trình Tạo Bài Thi Thực Hành',
    'practiceexam.subtitle': 'Tạo Bài Thi Được Hỗ Trợ bởi AI',
    
    // Exam Simulator
    'examsimulator.time' : 'Thời gian thi',
    'examsimulator.time.tip' : 'Thêm giới hạn thời gian tính bằng phút như một kỳ thi thật. Nếu không, hãy nhập một số bạn muốn',
    'examsimulator.title': 'Trình Mô Phỏng Bài Thi',
    'examsimulator.subtitle': 'Tạo chuỗi bài thi với độ khó tăng dần',
    'examsimulator.hero.title': 'Tạo Bài Thi Thực Hành Ngay Lập Tức',
    'examsimulator.hero.description': 'Tạo bài thi thực hành toàn diện từ tài liệu học tập của bạn. Tải lên tài liệu hoặc mô tả yêu cầu bài thi, và AI của chúng tôi sẽ tạo chuỗi bài thi chuyên nghiệp cho bạn.',
    'examsimulator.name.title': 'Đặt Tên Chuỗi Bài Thi Của Bạn',
    'examsimulator.name.placeholder': 'ví dụ: Chuỗi Thực Hành Giải Tích Nâng Cao, Chuẩn Bị Thi Cuối Sinh Học, Bootcamp Toán SAT...',
    'examsimulator.name.tip': 'Đặt cho chuỗi bài thi của bạn một cái tên dễ nhớ để dễ dàng nhận diện sau này',
    'examsimulator.describe.title': 'Mô Tả Chủ Đề Bài Thi Của Bạn',
    'examsimulator.describe.placeholder': 'ví dụ: Các khái niệm Giải Tích Nâng Cao bao gồm đạo hàm, tích phân và phương trình vi phân...',
    'examsimulator.describe.tip': 'Mô tả nội dung môn học và các chủ đề cụ thể bạn muốn được kiểm tra',
    'examsimulator.upload.title': 'Tải Lên Tài Liệu Tham Khảo (Tùy Chọn)',
    'examsimulator.upload.click': 'Nhấp để tải lên tài liệu tham khảo',
    'examsimulator.upload.support': 'Hỗ trợ tệp PDF, DOC, DOCX, TXT, JPG, PNG (Tối đa 10MB mỗi tệp)',
    'examsimulator.upload.files': 'Tệp Đã Tải Lên:',
    'examsimulator.settings.title': 'Cài Đặt Trình Mô Phỏng',
    'examsimulator.settings.show': 'Hiển Thị Cài Đặt Trình Mô Phỏng',
    'examsimulator.settings.hide': 'Ẩn Cài Đặt Trình Mô Phỏng',
    'examsimulator.exams.number': 'Số Lượng Bài Thi Tăng Dần',
    'examsimulator.exams.single': 'Cấp Độ Đơn',
    'examsimulator.exams.basic': 'Cơ Bản → Nâng Cao',
    'examsimulator.exams.expert': 'Cơ Bản → Chuyên Gia',
    'examsimulator.exams.foundation': 'Nền Tảng → Chuyên Gia',
    'examsimulator.exams.genius': 'Nền Tảng → Thiên Tài',
    'examsimulator.exams.tip': 'Mỗi bài thi tăng độ khó. Nếu bạn có thể đạt 80%+ trong bài thi cuối, bạn đã thành thạo chủ đề!',
    'examsimulator.difficulty.title': 'Các Cấp Độ Khó Tăng Dần',
    'examsimulator.difficulty.foundation': 'Nền Tảng',
    'examsimulator.difficulty.beginner': 'Người Mới Bắt Đầu',
    'examsimulator.difficulty.intermediate': 'Trung Cấp',
    'examsimulator.difficulty.advanced': 'Nâng Cao',
    'examsimulator.difficulty.expert': 'Chuyên Gia',
    'examsimulator.difficulty.master': 'Bậc Thầy',
    'examsimulator.difficulty.genius': 'Thiên Tài',
    'examsimulator.generate': 'Tạo Bài Thi Thực Hành',
    'examsimulator.generating': 'Đang Tạo Chuỗi Bài Thi...',
    'examsimulator.generating.description': 'Tạo bài thi với độ khó tăng dần bằng AI...',
    'examsimulator.saved.title': 'Chuỗi Bài Thi Đã Lưu',
    'examsimulator.saved.show': 'Tải Chuỗi Đã Lưu',
    'examsimulator.saved.hide': 'Ẩn',
    'examsimulator.saved.empty': 'Không tìm thấy chuỗi bài thi đã lưu. Tạo chuỗi đầu tiên của bạn để xem tại đây!',
    'examsimulator.saved.created': 'Đã Tạo',
    'examsimulator.saved.exams': 'bài thi',
    'examsimulator.saved.load': 'Tải Chuỗi',
    'examsimulator.error.title': 'Lỗi Tạo',
    'examsimulator.error.description': 'Tạo chuỗi bài thi thất bại',
    'examsimulator.error.try': 'Thử Lại',
    'examsimulator.error.reset': 'Đặt Lại Biểu Mẫu',
    'practiceexam.hero.title': 'Tạo Bài Thi Thực Hành Ngay Lập Tức',
    'practiceexam.hero.description': 'Tạo bài thi thực hành toàn diện từ tài liệu học tập của bạn. Tải lên tài liệu hoặc mô tả yêu cầu bài thi, và AI của chúng tôi sẽ tạo bài thi PDF chuyên nghiệp cho bạn.',
    'practiceexam.description.title': 'Mô Tả Bài Thi',
    'practiceexam.description.what': 'Bài thi này nên bao gồm những gì?',
    'practiceexam.description.placeholder': 'ví dụ: Giới thiệu về các khái niệm Học Máy bao gồm học có giám sát, mạng nơ-ron và đánh giá mô hình...',
    'practiceexam.description.tip': 'Mẹo: Hãy cụ thể về chủ đề, mức độ khó và bất kỳ lĩnh vực cụ thể nào bạn muốn tập trung.',
    'practiceexam.upload.title': 'Tải Lên Tài Liệu Tham Khảo',
    'practiceexam.upload.click': 'Nhấp để tải lên tệp',
    'practiceexam.upload.support': 'Hỗ trợ tệp PDF, DOC, DOCX, TXT (Tối đa 10MB mỗi tệp)',
    'practiceexam.upload.files': 'Tệp Đã Tải Lên:',
    'practiceexam.settings': 'Cài Đặt',
    'practiceexam.exam.settings': 'Cài Đặt Bài Thi',
    'practiceexam.questions.count': 'Số Lượng Câu Hỏi',
    'practiceexam.time.limit': 'Giới Hạn Thời Gian (phút)',
    'practiceexam.difficulty': 'Mức Độ Khó',
    'practiceexam.question.types': 'Loại Câu Hỏi',
    'practiceexam.answer.key': 'Bao Gồm Đáp Án',
    'practiceexam.generate': 'Tạo Bài Thi Thực Hành',
    'practiceexam.generating': 'Đang Tạo Bài Thi...',
    'practiceexam.success': 'Tạo Bài Thi Thành Công!',
    'practiceexam.ready': 'Sẵn sàng để tải xuống',
    'practiceexam.questions': 'Câu Hỏi:',
    'practiceexam.time': 'Thời Gian:',
    'practiceexam.download': 'Tải Xuống PDF',
    'practiceexam.preview': 'Xem Trước',
    'practiceexam.reset': 'Đặt Lại',
    'practiceexam.how.works': 'Cách Hoạt Động',
    'practiceexam.create': 'Tạo bài thi thực hành hoàn hảo của bạn',
    
    // Difficulty levels
    'difficulty.easy': 'Dễ',
    'difficulty.medium': 'Trung Bình',
    'difficulty.hard': 'Khó',
    'difficulty.mixed': 'Hỗn Hợp',
    'difficulty.beginner': 'Người Mới Bắt Đầu',
    'difficulty.intermediate': 'Trung Cấp',
    'difficulty.advanced': 'Nâng Cao',
    
    // Common
    'common.back': 'Quay Lại',
    'common.loading': 'Đang Tải...',
    'common.error': 'Lỗi',
    'common.success': 'Thành Công',
    'common.cancel': 'Hủy',
    'common.save': 'Lưu',
    'common.delete': 'Xóa',
    'common.edit': 'Chỉnh Sửa',
    'common.close': 'Đóng',
    'common.ok': 'OK',
    'common.yes': 'Có',
    'common.no': 'Không',
    'common.language': 'Ngôn Ngữ',
    
    // Auth
    'auth.signin': 'Đăng Nhập',
    'auth.signup': 'Đăng Ký',
    'auth.email': 'Email',
    'auth.password': 'Mật Khẩu',
    'auth.forgot': 'Quên Mật Khẩu?',
    'auth.no.account': 'Chưa có tài khoản?',
    'auth.have.account': 'Đã có tài khoản?',
    'auth.signing.in': 'Đang đăng nhập...',
    'auth.test.login': 'Tự Động Điền Đăng Nhập Thử Nghiệm',
    'auth.terms': 'Bằng cách đăng nhập, bạn đồng ý với Điều Khoản Dịch Vụ, Chính Sách Sử Dụng Chấp Nhận Được và Chính Sách Bảo Mật.',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  useEffect(() => {
    // Set document language attribute
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};